<?php

/**
 * 30 coordinated website color palettes.
 * Keys map to CSS vars: accent, accent_hover, primary, secondary, gray.
 */
return [
    'sky' => [
        'name_ar' => 'سماوي',
        'name_en' => 'Sky Blue',
        'accent' => '#009CCC',
        'accent_hover' => '#008CB8',
        'primary' => '#1C2B3D',
        'secondary' => '#32B4DC',
        'gray' => '#78828C',
    ],
    'ocean' => [
        'name_ar' => 'محيط عميق',
        'name_en' => 'Deep Ocean',
        'accent' => '#0284C7',
        'accent_hover' => '#0369A1',
        'primary' => '#0C4A6E',
        'secondary' => '#38BDF8',
        'gray' => '#64748B',
    ],
    'azure' => [
        'name_ar' => 'أزرق صافي',
        'name_en' => 'Azure',
        'accent' => '#2563EB',
        'accent_hover' => '#1D4ED8',
        'primary' => '#1E3A5F',
        'secondary' => '#60A5FA',
        'gray' => '#6B7C93',
    ],
    'ice' => [
        'name_ar' => 'ثلجي',
        'name_en' => 'Ice Blue',
        'accent' => '#0EA5E9',
        'accent_hover' => '#0284C7',
        'primary' => '#164E63',
        'secondary' => '#7DD3FC',
        'gray' => '#94A3B8',
    ],
    'sapphire' => [
        'name_ar' => 'ياقوتي',
        'name_en' => 'Sapphire',
        'accent' => '#1D4ED8',
        'accent_hover' => '#1E40AF',
        'primary' => '#172554',
        'secondary' => '#3B82F6',
        'gray' => '#64748B',
    ],
    'navy' => [
        'name_ar' => 'كحلي ليلي',
        'name_en' => 'Navy Night',
        'accent' => '#1E40AF',
        'accent_hover' => '#1E3A8A',
        'primary' => '#0F172A',
        'secondary' => '#3B82F6',
        'gray' => '#64748B',
    ],
    'indigo' => [
        'name_ar' => 'نيلي',
        'name_en' => 'Indigo',
        'accent' => '#4F46E5',
        'accent_hover' => '#4338CA',
        'primary' => '#1E1B4B',
        'secondary' => '#818CF8',
        'gray' => '#6B7280',
    ],
    'lavender' => [
        'name_ar' => 'لافندر',
        'name_en' => 'Lavender',
        'accent' => '#7C3AED',
        'accent_hover' => '#6D28D9',
        'primary' => '#2E1065',
        'secondary' => '#A78BFA',
        'gray' => '#78716C',
    ],
    'violet' => [
        'name_ar' => 'بنفسجي ملكي',
        'name_en' => 'Royal Violet',
        'accent' => '#9333EA',
        'accent_hover' => '#7E22CE',
        'primary' => '#3B0764',
        'secondary' => '#C084FC',
        'gray' => '#6B7280',
    ],
    'orchid' => [
        'name_ar' => 'أوركيد',
        'name_en' => 'Orchid',
        'accent' => '#C026D3',
        'accent_hover' => '#A21CAF',
        'primary' => '#4A044E',
        'secondary' => '#E879F9',
        'gray' => '#78716C',
    ],
    'rose' => [
        'name_ar' => 'وردي ناعم',
        'name_en' => 'Soft Rose',
        'accent' => '#E11D48',
        'accent_hover' => '#BE123C',
        'primary' => '#4C0519',
        'secondary' => '#FB7185',
        'gray' => '#78716C',
    ],
    'crimson' => [
        'name_ar' => 'قرمزي',
        'name_en' => 'Crimson',
        'accent' => '#DC2626',
        'accent_hover' => '#B91C1C',
        'primary' => '#450A0A',
        'secondary' => '#F87171',
        'gray' => '#78716C',
    ],
    'burgundy' => [
        'name_ar' => 'عنابي',
        'name_en' => 'Burgundy',
        'accent' => '#9F1239',
        'accent_hover' => '#881337',
        'primary' => '#4C0519',
        'secondary' => '#E11D48',
        'gray' => '#6B7280',
    ],
    'coral' => [
        'name_ar' => 'مرجان',
        'name_en' => 'Coral',
        'accent' => '#F43F5E',
        'accent_hover' => '#E11D48',
        'primary' => '#3F1D2E',
        'secondary' => '#FB7185',
        'gray' => '#78716C',
    ],
    'peach' => [
        'name_ar' => 'خوخ',
        'name_en' => 'Peach',
        'accent' => '#FB7185',
        'accent_hover' => '#F43F5E',
        'primary' => '#4A2C2A',
        'secondary' => '#FDA4AF',
        'gray' => '#8B7E74',
    ],
    'orange' => [
        'name_ar' => 'برتقالي دافئ',
        'name_en' => 'Warm Orange',
        'accent' => '#EA580C',
        'accent_hover' => '#C2410C',
        'primary' => '#431407',
        'secondary' => '#FB923C',
        'gray' => '#78716C',
    ],
    'amber' => [
        'name_ar' => 'كهرماني',
        'name_en' => 'Amber',
        'accent' => '#D97706',
        'accent_hover' => '#B45309',
        'primary' => '#451A03',
        'secondary' => '#FBBF24',
        'gray' => '#78716C',
    ],
    'gold' => [
        'name_ar' => 'ذهبي',
        'name_en' => 'Gold',
        'accent' => '#CA8A04',
        'accent_hover' => '#A16207',
        'primary' => '#422006',
        'secondary' => '#EAB308',
        'gray' => '#78716C',
    ],
    'copper' => [
        'name_ar' => 'نحاسي',
        'name_en' => 'Copper',
        'accent' => '#C2410C',
        'accent_hover' => '#9A3412',
        'primary' => '#431407',
        'secondary' => '#F97316',
        'gray' => '#78716C',
    ],
    'forest' => [
        'name_ar' => 'غابة خضراء',
        'name_en' => 'Forest',
        'accent' => '#15803D',
        'accent_hover' => '#166534',
        'primary' => '#14532D',
        'secondary' => '#4ADE80',
        'gray' => '#6B7280',
    ],
    'emerald' => [
        'name_ar' => 'زمردي',
        'name_en' => 'Emerald',
        'accent' => '#059669',
        'accent_hover' => '#047857',
        'primary' => '#064E3B',
        'secondary' => '#34D399',
        'gray' => '#6B7280',
    ],
    'mint' => [
        'name_ar' => 'نعناع',
        'name_en' => 'Mint',
        'accent' => '#10B981',
        'accent_hover' => '#059669',
        'primary' => '#134E4A',
        'secondary' => '#6EE7B7',
        'gray' => '#6B7280',
    ],
    'teal' => [
        'name_ar' => 'تيل عميق',
        'name_en' => 'Deep Teal',
        'accent' => '#0D9488',
        'accent_hover' => '#0F766E',
        'primary' => '#134E4A',
        'secondary' => '#2DD4BF',
        'gray' => '#64748B',
    ],
    'turquoise' => [
        'name_ar' => 'تركواز',
        'name_en' => 'Turquoise',
        'accent' => '#14B8A6',
        'accent_hover' => '#0D9488',
        'primary' => '#115E59',
        'secondary' => '#5EEAD4',
        'gray' => '#6B7280',
    ],
    'cyan' => [
        'name_ar' => 'فيروزي',
        'name_en' => 'Cyan',
        'accent' => '#06B6D4',
        'accent_hover' => '#0891B2',
        'primary' => '#164E63',
        'secondary' => '#22D3EE',
        'gray' => '#64748B',
    ],
    'olive' => [
        'name_ar' => 'زيتوني',
        'name_en' => 'Olive',
        'accent' => '#65A30D',
        'accent_hover' => '#4D7C0F',
        'primary' => '#365314',
        'secondary' => '#A3E635',
        'gray' => '#6B7280',
    ],
    'matcha' => [
        'name_ar' => 'شاي أخضر',
        'name_en' => 'Matcha',
        'accent' => '#84CC16',
        'accent_hover' => '#65A30D',
        'primary' => '#3F6212',
        'secondary' => '#BEF264',
        'gray' => '#6B7280',
    ],
    'lime' => [
        'name_ar' => 'ليموني',
        'name_en' => 'Lime',
        'accent' => '#22C55E',
        'accent_hover' => '#16A34A',
        'primary' => '#14532D',
        'secondary' => '#4ADE80',
        'gray' => '#6B7280',
    ],
    'slate' => [
        'name_ar' => 'رمادي أنيق',
        'name_en' => 'Elegant Slate',
        'accent' => '#475569',
        'accent_hover' => '#334155',
        'primary' => '#0F172A',
        'secondary' => '#94A3B8',
        'gray' => '#64748B',
    ],
    'charcoal' => [
        'name_ar' => 'فحمي',
        'name_en' => 'Charcoal',
        'accent' => '#374151',
        'accent_hover' => '#1F2937',
        'primary' => '#111827',
        'secondary' => '#6B7280',
        'gray' => '#9CA3AF',
    ],
];
